version: 2.1

jobs:
    "server-test":
        docker:
            - image: circleci/python:3.9.2-buster-node-browsers
              environment:
                PERCY_PARALLEL_TOTAL: -1
            - image: cypress/base:10
        steps:
            - checkout
            - run:
                name: Inject Percy Environment variables
                command: |
                  echo 'export PERCY_TOKEN="$PERCY_TOKEN_E2E"' >> $BASH_ENV
            - run:
                name: Install npm packages
                command: npm ci
            - run:
                name: Install requirements
                command: |
                    pip install --upgrade virtualenv
                    python -m venv venv || virtualenv venv
                    . venv/bin/activate
                    pip install -r dev-requirements.txt --quiet
                    git clone --depth 1 git@github.com:plotly/dash.git dash-main
                    pip install -e ./dash-main[dev,testing] --quiet
                    cd dash-main/dash-renderer && npm ci && npm run build && pip install -e . && cd ./../..
            - run:
                name: Build
                command: |
                    . venv/bin/activate
                    npm run private::build:js-test
                    npm run private::build:backends
                    python setup.py sdist
                    cd dist
                    find . -name "*.gz" | xargs pip install --no-cache-dir --ignore-installed && cd ..
            - run:
                name: Run tests
                command: |
                    . venv/bin/activate
                    npm run test.server
            - run:
                name: 🦔 percy finalize
                command: npx percy finalize --all
                when: always

    "standalone-test":
        docker:
            - image: circleci/python:3.9.2-buster-node-browsers
            - image: cypress/base:10
        steps:
            - checkout
            - run:
                name: Install npm packages
                command: npm ci
            - run:
                name: Cypress Install
                command: |
                    $(npm bin)/cypress install
            - run:
                name: Run tests
                command: |
                    npm run test.standalone

    "unit-test":
        docker:
            - image: circleci/python:3.9.2-buster-node-browsers
        steps:
            - checkout
            - run:
                name: Install npm packages
                command: npm ci
            - run:
                name: Install requirements
                command: |
                    pip install --upgrade virtualenv
                    python -m venv venv || virtualenv venv
                    . venv/bin/activate
                    pip install -r dev-requirements.txt --quiet
                    pip install --progress-bar off -e git+https://github.com/plotly/dash.git@dev#egg=dash[dev,testing]
            - run:
                name: Run tests
                command: |
                    . venv/bin/activate
                    npm run test.unit

    "visual-test":
        docker:
            - image: circleci/node:14-browsers
        steps:
            - checkout
            - run:
                name: Install package.json
                command: npm ci
            - run:
                name: Run build:js
                command: npm run private::build:js
            - run:
                name: Run visual tests
                command: npm run test.visual
            - store_artifacts:
                path: storybook-static

    "node":
        docker:
            - image: circleci/python:3.9.2-node
        steps:
            - checkout
            - run:
                  name: Create virtual env
                  command: python -m venv || virtualenv venv
            - run:
                name: Install package.json
                command: npm ci
            - run:
                name: Install requirements
                command: |
                    . venv/bin/activate
                    pip install -r dev-requirements.txt --quiet
                    pip install --progress-bar off -e git+https://github.com/plotly/dash.git@dev#egg=dash[dev,testing]
            - run:
                name: Run eslint
                command: |
                    . venv/bin/activate
                    npm run lint
                when: always

workflows:
    version: 2
    build:
        jobs:
            - "node"
            - "server-test"
            - "standalone-test"
            - "unit-test"
            - "visual-test"
